[package]
name = "neat-theme"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Vadim Zyamalov <@vadim-zyamalov>"]
license = "MIT"
description = "Simple touying theme satisfying my personal requiremens."
