[package]
name = "trinkets"
version = "0.1.0"
entrypoint = "trinkets.typ"
authors = ["Vadim Zyamalov <@vadim-zyamalov>"]
license = "MIT"
description = "Various math functions and operators, missing in default typst."
